### PR TITLE
Remove copyright

### LINKED ISSUE #2: Copyright?
Well I'm not sure about this
image
we don't actually own the website  
we should just put "Built with portflowio"

### PR DESCRIPTION
**Pull request by ghost**
eh cf #2

### CODE REVIEW

**Comment by moeenio** [comment]
why

**Comment by ghost** [comment]
because a website that uses portflowio isn't owned by portflowio >:(

**Comment by moeenio** [comment]
fair

**Comment by ghost** [comment]
yeet thank u

**Pull request merged**
