### PR TITLE
various changes

### PR DESCRIPTION
**Pull request by moeenio**
- remove old files such as add.php that moved to the admin folder
- dont store password in session data
- make more code into english
- other various changes

### CODE REVIEW

**Comment by ghost** [comment]
What a descriptive name

**Comment by moeenio** [comment]
thanks

**Comment by Rexxt** [comment]
Very amazing

**Comment by moeenio** [comment]
wot thanks lol

**Comment by ecnivtwelve** [comment]
panel and add were already in admin normally, but thanks for these changes :)

**Pull request merged**
